=== Bootstrap

include::./../../../variable.adoc[]
:example: ../../../{mainJavaDir}/builder/boot/ServiceRegisterExample.java


First step. Queryman builder requires to place either `queryman-configuration.xml`
 or `queryman-configuration.properties` into *resource* directory.
 If this step is not completed, `IOException` is raised.

Second step - initialization. It is done by one line:
[source,java]
include::{example}[tag=simple-register]


`ServiceRegister` relies on `MetadataBuilder` that is used to populate metadata
from one of the above configuration file. You can change a builder by implement
`MetadataBuilder` interface or use an existing implementation of it then set it:
[source,java]
include::{example}[tag=provide-builder]

To change a location of configuration file or a name of file use one of methods:
`setXmlCfg(String name)` or `setPropertiesCfg(String name)`:

[source,java]
include::{example}[tag=change-xml-file]

[source,java]
include::{example}[tag=change-properties-file]

It is possible to provide your own `Metadata`.
Note, the metadata from configuration file takes precedence over the metadata
provided by user.
[source,java]
```
include::{example}[tag=custom-metadata]
```

More details of configuration is described in the {builderDocs}/userguide/index.html[section].
