[[bootstrap]]
== Bootstrap

include::./../variable.adoc[]
:example: ../{mainJavaDir}/boot/ServiceRegisterExample.java

[NOTE]
At first. You should deal bootstrap only when the default {domainDocs}/userguide/settings.html[settings]
are not suitable for your project.

By default the settings can be derived either in xml file (is named `queryman-builder.xml`)
 or properties file (is named `queryman-builder.properties`). Then the `ServiceRegister`
 must be called:
[source,java]
include::{example}[tag=simple-register]

You can change name of the above files using one of below ways:
[source,java]
```
include::{example}[tag=change-xml-file]
```

[NOTE]
The settings files must locate in *resource* catalog

*How configuration is loaded.*

First, `ServiceRegister` tries to load the *xml* configuration. If this attempt is failed,
then it will try to load a configuration from *properties* file. If this attempt is
failed too, the default configuration will be used.

There after, you should provide `TreeFactory` into `PostgreSQL`:
[source,java]
include::{example}[tag=get-tree-factory]
