[[expressions]]
=== Expressions

include::./../variable.adoc[]
:example: ../{mainJavaDir}/QuerymanExamples.java

The expressions are used in a variety context, almost by all of clauses, like
output list in SELECT clause, table name or subquery in FROM clause, WHERE clause operates
scalar, row, subquery expressions etc in its own conditions.

The `Queryman` class provides convenient methods creating any expressions. Some examples
described a creation of expression are below. But, before starting a explanation
of them, look at common methods such as AS and CAST which all expressions are possessed.


==== Alias

A brief introduction into PostgreSQL aliases. The alias can be applied for any expression
such as a column, a table, a subquery, etc. The alias hides an original name
of object for which it is used. In other words, it becomes a new reference on
object.

Alias is applicable for all expressions. The common example is:
[source,java]
```
include::{example}[tag=alias]
```

Keeping on the above definition look at the below example. If change the alias
name `b` on table name `book` in the SELECT output list, the error will occurs:
```
[42P01] ERROR: invalid reference to FROM-clause entry for table "book"
```
[source,java]
```
include::{example}[tag=select-alias]
```


==== Explicitly casting

Queryman allows an explicitly casting any expression to particular type:
[source,java]
include::{example}[tag=cast]

One more feature is a use explicit casting for building prepared statement:
[source,java]
include::{example}[tag=prepared]


==== Expression methods

Queryman provides several helpful methods to work with different date types


===== Constants: Queryman.asConstant() and other constant-methods

PostgreSQL constants are numeric, string, date/time, arrays and other data types.

This method allows working with the following Java types:

* primitives and their wrappers
* `java.sql.Date`, `java.sql.Time`, `java.sql.Timestamp`, `java.util.Date`
* `java.math.BigDecimal`
* arrays
* UUID

The `java.util.Date` type is converted into `java.sql.Date`. If you wish to
be in control into which PostgreSQL type it is converted, use one of ad hoc methods:

* `Queryman.asDate`
* `Queryman.asTime`
* `Queryman.asTimestamp`

Some of examples of constant expressions are:
[source,java]
include::{example}[tag=constant]


There are a few other useful methods deal constants:

* `Queryman.asDollarString`
* `Queryman.asArray`


Example using of `asArray` method:
[source,java]
include::{example}[tag=array]

All Queryman constants may be used for building a string SQL or a SQL that contains
prepared statement.

[source,java]
include::{example}[tag=insert-prepared]


===== Column reference: Queryman.asName, Queryman.asQuotedName

These methods are used to denote name of object. The passed argument into them
may be a a string contains one of qualified name or an unqualified name.

The output of them is either quoted name or unquoted name.
[source,java]
include::{example}[tag=column-reference]

===== List constructor: Queryman.asList
The list constructor takes list of arguments and builds them into PostgreSQL's list
compatible form. The PostgreSQL's list is values are separated by commas and
surrounded by parentheses. An argument may be any type.

[source,java]
include::{example}[tag=list]

===== Subquery: Queryman.asSubquery
Subquery are used in a variety statements. Its common using is:
[source,java]
include::{example}[tag=query]

SELECT clause using subquery:
[source,java]
include::{example}[tag=select-query]

EXISTS clause using subquery:
[source,java]
include::{example}[tag=exists-query]

===== Function calls
Examples of function expression:
[source,java]
```
include::{example}[tag=func]
```

===== Extending expression

You may easily add your own expression implementation by extending the
`org.queryman.builder.token.Expressing` class.